spring:
  application:
    name: IntuitCraftDemoProject
# PostgreSQL database connection settings
  datasource:
    url: jdbc:postgresql://localhost:5432/intuitdemo
    username: intuitdemo
#    password:
    driver-class-name: org.postgresql.Driver

# JPA and Hibernate settings
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
